sudo: false

language: python

python:
  - '2.7'
  - '3.4'
  - pypy

env:
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
