sudo: false

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
